### PR TITLE
[Issue-69] Fix some style bug

### LINKED ISSUE #69: Style Problems Review
- [x] Restructure the storybook menu
- [x] Wrong font-weight: Font-weight 500 is not applied globally (for ex: typo, input)
- [x] Address lack of number character option
- [x] Form demo lack of global error
- [x] QRCode: Icon should be default
- [x] Logo Need more example case
  - [x] Show network
  - [x] Show token
- [x] Update Activity Indicator like button
- [x] Confirm: Ghost button color
- [x] Confirm: SwModal: Re-design when hover button X
image

- [x] Confirm: The number's styles on list with the number's style on typo
image

### PR DESCRIPTION
**Pull request by Quangdm-cdm**
Pr for issue #69

### CODE REVIEW

File: components/qrcode/index.tsx [hunk 1]
```diff
@@ -17,7 +17,8 @@ const { useToken } = theme;
 const QRCode: React.FC<QRCodeProps> = (props) => {
   const {
     value,
-    icon = '',
+    // eslint-disable-next-line global-require
+    icon = require('./QrCodeIcon.png'),
```
Comment (saltict) [inline components/qrcode/index.tsx]: Use new const for this png require

**Review by saltict — APPROVED** [review]
